version: '2'
services:
  web:
    image: httpd
    ports:
      - "8080:80"
    volumes:
      - ./web:/usr/local/apache2/htdocs
    links:
      - solr
    depends_on:
      - solr
  solr:
    image: solr
    ports:
      - "8983:8983"